#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service
        if [ -d /run/systemd/system ]; then
            systemctl stop dns-proxy.service >/dev/null || true
        fi
        ;;
    
    failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
